### ISSUE TITLE
Switch Backend from CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by KrisVan** [PickLe-Time/pickletime-backend#3]
Do for frontend and backend repos
- [ ] Frontend
- [x] Backend

### Instructions
Create the following file in your repo:
```.github/workflows/ci.yml```
```
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Update to match your project's Node version

      - name: Install dependencies
        run: npm install

      - name: Enforce code styles
        run: npm run lint

      - name: Run tests
        run: npm run test
```
